import { Profile } from "./interfaces" 

export const profiles: Profile[] = [
  { profileId: 0, accountId: 0, country: 'country0', marketplace: 'marketplace0' },
  { profileId: 1, accountId: 1, country: 'country1', marketplace: 'marketplace1' },
  { profileId: 2, accountId: 2, country: 'country1', marketplace: 'marketplace1' },
  { profileId: 3, accountId: 2, country: 'country2', marketplace: 'marketplace2' },
  { profileId: 4, accountId: 0, country: 'country2', marketplace: 'marketplace3' },
  { profileId: 5, accountId: 3, country: 'country3', marketplace: 'marketplace4' },
  { profileId: 6, accountId: 1, country: 'country2', marketplace: 'marketplace2' },
  { profileId: 7, accountId: 3, country: 'country2', marketplace: 'marketplace2' },
  { profileId: 8, accountId: 1, country: 'country4', marketplace: 'marketplace5' },
  { profileId: 9, accountId: 0, country: 'country2', marketplace: 'marketplace3' },
  { profileId: 10, accountId: 2, country: 'country3', marketplace: 'marketplace4' },
  { profileId: 11, accountId: 4, country: 'country4', marketplace: 'marketplace6' },
  { profileId: 12, accountId: 4, country: 'country1', marketplace: 'marketplace1' },
  { profileId: 13, accountId: 5, country: 'country5', marketplace: 'marketplace0' },
  { profileId: 14, accountId: 7, country: 'country1', marketplace: 'marketplace1' },
  { profileId: 15, accountId: 8, country: 'country2', marketplace: 'marketplace3' },
  { profileId: 16, accountId: 6, country: 'country2', marketplace: 'marketplace3' },
  { profileId: 17, accountId: 7, country: 'country3', marketplace: 'marketplace4' },
  { profileId: 18, accountId: 5, country: 'country4', marketplace: 'marketplace6' },
  { profileId: 19, accountId: 8, country: 'country4', marketplace: 'marketplace7' },
  { profileId: 20, accountId: 8, country: 'country1', marketplace: 'marketplace1' },
  { profileId: 21, accountId: 7, country: 'country4', marketplace: 'marketplace5' },
  { profileId: 22, accountId: 9, country: 'country5', marketplace: 'marketplace8' },
  { profileId: 23, accountId: 10, country: 'country6', marketplace: 'marketplace9' },
  { profileId: 24, accountId: 10, country: 'country5', marketplace: 'marketplace0' },
  { profileId: 25, accountId: 11, country: 'country0', marketplace: 'marketplace0' },
  { profileId: 26, accountId: 12, country: 'country1', marketplace: 'marketplace1' },
  { profileId: 27, accountId: 12, country: 'country2', marketplace: 'marketplace2' },
  { profileId: 28, accountId: 13, country: 'country0', marketplace: 'marketplace0' },
  { profileId: 29, accountId: 14, country: 'country5', marketplace: 'marketplace0' },
  { profileId: 30, accountId: 15, country: 'country4', marketplace: 'marketplace6' },
  { profileId: 31, accountId: 15, country: 'country4', marketplace: 'marketplace5' },
  { profileId: 32, accountId: 16, country: 'country3', marketplace: 'marketplace4' },
  { profileId: 33, accountId: 16, country: 'country2', marketplace: 'marketplace3' },
  { profileId: 34, accountId: 16, country: 'country5', marketplace: 'marketplace8' },
  { profileId: 35, accountId: 17, country: 'country3', marketplace: 'marketplace4' },
  { profileId: 36, accountId: 17, country: 'country0', marketplace: 'marketplace0' },
  { profileId: 37, accountId: 18, country: 'country1', marketplace: 'marketplace1' },
  { profileId: 38, accountId: 19, country: 'country2', marketplace: 'marketplace3' },
  { profileId: 39, accountId: 20, country: 'country0', marketplace: 'marketplace0' },
  { profileId: 40, accountId: 20, country: 'country1', marketplace: 'marketplace1' },
  { profileId: 41, accountId: 21, country: 'country2', marketplace: 'marketplace2' },
]